In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.metrics import classification_report

In [39]:
import pickle

In [40]:
df=pd.read_csv('XOM UN Equity.csv')
len(df.columns)

18

In [41]:
len(df)

1304

In [42]:
df.dropna(axis=0,inplace=True)

In [43]:
df.isnull().sum()

Variables                        0
TWITTER_SENTIMENT_DAILY_AVG      0
TWITTER_PUBLICATION_COUNT        0
TWITTER_POS_SENTIMENT_COUNT      0
TWITTER_NEG_SENTIMENT_COUNT      0
TWITTER_NEUTRAL_SENTIMENT_CNT    0
PX_OPEN                          0
PX_LOW                           0
PX_HIGH                          0
EQY_WEIGHTED_AVG_PX              0
VWAP_VOLUME                      0
VWAP_TURNOVER                    0
VWAP_NUM_TRADES                  0
NEWS_SENTIMENT_DAILY_AVG         0
NEWS_NEUTRAL_SENTIMENT_COUNT     0
NEWS_POS_SENTIMENT_COUNT         0
NEWS_NEG_SENTIMENT_COUNT         0
NEWS_PUBLICATION_COUNT           0
dtype: int64

In [44]:
algo=['Linear Regression',
'Ridge Regression',
'Lasso',
'SVR (Linear)',
'SVR (rbf)',
'Decision Tree',
'Random Forest',
'Elastic Net',
'Gradient Boost',
]

In [45]:
l=['base11.sav','base22.sav','base33.sav','base44.sav','base5.sav','base66.sav','base77.sav','base88.sav','base99.sav']
#these are all the base models with their names corresponding to algos respectively

In [46]:
def make_bases(df):
    X=df.drop(['Variables','PX_HIGH'],axis=1)
    y=df['PX_HIGH']
    start={'PX_HIGH':y}
    pred=pd.DataFrame(start)
    mae=[]
    mse=[]
    rmse=[]
    score=[]
    metric=pd.DataFrame(index=algo)
    row=0
    for i in l:
        
        loaded_model = pickle.load(open(i, 'rb'))     #loading the model one by one which are named  according to the elements in list l
        result = loaded_model.score(X, y)
        
        prediction=loaded_model.predict(X)
        print(result,i,r2_score(y,prediction))
        pred[i]=prediction
        print('MAE:', metrics.mean_absolute_error(y, prediction))
        print('MSE:', metrics.mean_squared_error(y, prediction))
        print('RMSE:', np.sqrt(metrics.mean_squared_error(y, prediction)))
        mae.append(metrics.mean_absolute_error(y, prediction))
        mse.append(metrics.mean_squared_error(y, prediction))
        rmse.append(np.sqrt(metrics.mean_squared_error(y, prediction)))
        score.append(r2_score(y,prediction))
        
    data={'models':algo,"RMSE":rmse,"R_2SCORE":score,"MAE":mae,'MSE':mse,}
    metric = pd.DataFrame(data)#create a dataframe including the metrics from all base models
    
        
        
  
         
        
    return pred,metric

In [47]:
datas,metric=make_bases(df)

0.9972147598498361 base11.sav 0.9972147598498361
MAE: 0.23753031460817964
MSE: 0.09999665233999966
RMSE: 0.31622247285732186
0.9971920810677553 base22.sav 0.9971920810677553
MAE: 0.23874368258891027
MSE: 0.10081087379487313
RMSE: 0.31750728148323326
0.9923794502302441 base33.sav 0.9923794502302441
MAE: 0.4473368853208548
MSE: 0.2735956057222209
RMSE: 0.5230636727227584
0.9954158908816126 base44.sav 0.9954158908816128
MAE: 0.3036551648202964
MSE: 0.16458026636339348
RMSE: 0.4056849348489459
-11.469159928233864 base5.sav -11.469159928233864
MAE: 13.960848635831455
MSE: 447.67207963811796
RMSE: 21.158262680052868
-3.589703502440813 base66.sav -3.5897035024408135
MAE: 11.381881134969325
MSE: 164.781117868865
RMSE: 12.836709775829046
-3.6346983973296005 base77.sav -3.6346983973296005
MAE: 11.458940627581423
MSE: 166.39654010130846
RMSE: 12.899478287950581
0.9901216436283419 base88.sav 0.9901216436283418
MAE: 0.5053429528878608
MSE: 0.3546561569310992
RMSE: 0.595530147793627
-4.238103279515767 base99.sav -4.238103279515767
MAE: 12.344446895387533
MSE: 188.06019026112602
RMSE: 13.713503938130692

In [48]:
 metric

              models       RMSE   R_2SCORE        MAE         MSE
0  Linear Regression   0.316222   0.997215   0.237530    0.099997
1   Ridge Regression   0.317507   0.997192   0.238744    0.100811
2              Lasso   0.523064   0.992379   0.447337    0.273596
3       SVR (Linear)   0.405685   0.995416   0.303655    0.164580
4          SVR (rbf)  21.158263 -11.469160  13.960849  447.672080
5      Decision Tree  12.836710  -3.589704  11.381881  164.781118
6      Random Forest  12.899478  -3.634698  11.458941  166.396540
7        Elastic Net   0.595530   0.990122   0.505343    0.354656
8     Gradient Boost  13.713504  -4.238103  12.344447  188.060190

In [49]:
datas

,PX_HIGH,base11.sav,base22.sav,base33.sav,base44.sav,base5.sav,base66.sav,base77.sav,base88.sav,base99.sav
0,93.130,92.883542,92.879530,92.673560,92.814725,97.756447,93.66,93.542264,92.671926,94.716084
1,93.050,93.044715,93.039186,92.768085,92.908379,95.170989,93.66,93.519397,92.666317,94.699471
2,92.400,91.861115,91.862533,91.331595,91.588522,93.809968,93.05,93.018533,91.271987,94.263681
3,91.410,90.926017,90.865076,90.501597,90.560249,124.248005,93.05,92.941011,90.422606,93.647854
4,91.470,91.195294,91.177779,90.936316,91.056905,95.251961,93.05,93.021493,90.886375,93.647854
...,...,...,...,...,...,...,...,...,...,...
1299,70.500,70.302253,70.300967,70.137837,70.389781,82.431071,92.78,92.926747,70.182194,94.168628
1300,70.499,70.293572,70.299771,70.196012,70.434548,89.037317,92.78,92.824774,70.226812,94.402623
1301,70.310,70.161584,70.158663,69.935438,70.116717,86.607136,93.05,92.941011,69.960006,94.170443
1302,70.430,69.893316,69.893302,69.764806,70.005839,100.635655,92.78,92.824774,69.769496,93.986792
1303,69.800,69.592520,69.598795,69.437140,69.630385,96.769716,92.78,92.824774,69.309186,93.986792

In [50]:
#TOP44.sav-Ridge Reg(on top) with (linear,ridge,lasso,svm,elastic net as base)

In [51]:
l1=['Proposed']

In [52]:
def final_model(datas):
    datas=datas.rename(columns={'base1.sav':'model_1','base22.sav':'model_2','base33.sav':'model_3','base44.sav':'model_4','base5.sav':'model_5','base66.sav':'model_6','base77.sav':'model_7','base88.sav':'model_8','base99.sav':'model_9'})
    X=datas.drop(['model_9','PX_HIGH','model_5','model_6','model_7'],axis=1)
    y=datas['PX_HIGH']
    loaded_model = pickle.load(open('top44.sav', 'rb'))
    result = loaded_model.score(X, y)    
    prediction=loaded_model.predict(X)
    mae=[]
    mse=[]
    rmse=[]
    score=[]
    metric=pd.DataFrame(index=l1)
    print(result,r2_score(y,prediction))
    
    print('MAE:', metrics.mean_absolute_error(y, prediction))
    print('MSE:', metrics.mean_squared_error(y, prediction))
    print('RMSE:', np.sqrt(metrics.mean_squared_error(y, prediction)))
    mae.append(metrics.mean_absolute_error(y, prediction))
    mse.append(metrics.mean_squared_error(y, prediction))
    rmse.append(np.sqrt(metrics.mean_squared_error(y, prediction)))
    score.append(r2_score(y,prediction))
    
    data={"models":l1,"RMSE":rmse,"R_2SCORE":score,"MAE":mae,'MSE':mse}
    metric = pd.DataFrame(data) 
    return metric

In [53]:
pro_metric=final_model(datas) #returning the datafrme  containing metrics of the proposed model

0.9972030024976174 0.9972030024976174
MAE: 0.2380103017702501
MSE: 0.10041876885378932
RMSE: 0.3168892059597318

In [54]:
#appending both the dataframe (containing accuracies of base and proposed model)
last=metric.append(pro_metric)

In [55]:
#sending the dataframe to matrixxx.csv file
last.to_csv('matrixxxx.csv', mode='a', index = False, header=metric.columns,columns=metric.columns)